# Use Ubuntu as the base image
FROM ubuntu:latest

# Update the package list and install httpd
RUN apt-get update && \
    apt-get -y install apache2 && \
    apt-get clean

# Copy your HTML file to the Apache web server directory
COPY webapp/index.html /var/www/html/

# Expose port 80 to allow external access
EXPOSE 80

# Command to start httpd in the foreground when the container starts
CMD ["/usr/sbin/apache2ctl", "-D", "FOREGROUND"]