spring:
  application:
    name: "ecs-app"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always # [always, when-authorize, never]
      status:
        http-mapping:
          DOWN: 503
          OUT_OF_SERVICE: 503
          UNKNOWN: 200
          UP: 200
logging:
  file:
    name: ./myapp.log